### ISSUE TITLE
How to expose container ports to localhost for secondary containers? 

### ISSUE THREAD

**Issue by kinluek** [CircleCI-Public/circleci-demo-go#16]
In the example config, you have this run command to see when the postgres service is ready:
```
      #  Wait for Postgres to be ready before proceeding
      - run:
          name: Waiting for Postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
```
But no where do I see you explicitly publishing the container port to the host port. What would happen if we ran two containers that exposed the same container port? How could would we be able to connect to them individually from the primary container?
